# Uncomment the next line to define a global platform for your project
# add pods for desired Firebase products

# https://firebase.google.com/docs/ios/setup#available-pods
target 'SportsMerch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportsMerch

end
